name: Ubuntu
on: [push, pull_request]
jobs:
  Ubuntu Run:
    runs-on: ubuntu-latest
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.4
        id: cuda-toolkit
        with:
          cuda: '11.2.2'
          linux-local-args: '["--toolkit"]'      
      - run: nvcc -V      
      - name: Checkout
        uses: actions/checkout@v2            
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build      
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../
      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j
      - run: echo "This job's status is ${{ job.status }}."
